CREATE ROLE flyway LOGIN PASSWORD 'flyway_ps' SUPERUSER CREATEDB CREATEROLE REPLICATION;
CREATE ROLE dashboard_api LOGIN PASSWORD 'dashboard_api_ps' CREATEDB CREATEROLE INHERIT;
CREATE ROLE dashboard_api_readonly LOGIN PASSWORD 'dashboard_api_readonly_ps' CREATEDB CREATEROLE INHERIT;

CREATE DATABASE "dashboardapidb";
