CREATE SCHEMA dashboard;

ALTER ROLE dashboard_api WITH NOCREATEDB NOCREATEROLE NOINHERIT;

GRANT USAGE ON SCHEMA dashboard TO dashboard_api;

ALTER DEFAULT PRIVILEGES IN SCHEMA dashboard GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO dashboard_api;
